export const storageKeys = {
  appSettings: "beit-cohen-shor-app-settings",
  tasks: "beit-cohen-shor-family-tasks",
  finance: "beit-cohen-shor-finance-transactions",
  financeBankBalance: "beit-cohen-shor-finance-bank-balance",
  financeSavingsBalance: "beit-cohen-shor-finance-savings-balance",
  financeLoansBalance: "beit-cohen-shor-finance-loans-balance",
  financeMortgageBalance: "beit-cohen-shor-finance-mortgage-balance",
  health: "beit-cohen-shor-health-records",
  documents: "beit-cohen-shor-documents",
  receiptDocuments: "beit-cohen-shor-receipt-documents",
  vehicles: "beit-cohen-shor-vehicle-records",
  family: "beit-cohen-shor-family-records",
  familyTree: "nestly-family-tree",
  birthdays: "beit-cohen-shor-birthdays",
  shopping: "beit-cohen-shor-shopping-items",
  permissions: "beit-cohen-shor-permissions",
  authSession: "nestly-auth-session",
  smartNudge: "nestly-smart-nudge",
} as const;
