import type {
  EntityRelationType,
  EntityRelationshipType,
} from "@/types/entityRelations";
import type { AppRoute } from "@/types/navigation";

export const entityTypeLabels: Record<EntityRelationType, string> = {
  task: "משימה",
  shopping_item: "פריט קנייה",
  shopping_list: "רשימת קניות",
  finance_transaction: "פעולה כספית",
  receipt: "קבלה",
  document: "מסמך",
  vehicle: "רכב",
  vehicle_reminder: "תזכורת רכב",
  family_member: "בן משפחה",
  family_event: "אירוע משפחתי",
  note: "פתק",
  family_knowledge: "מידע משפחתי",
  reminder: "תזכורת",
  smart_capture: "לכידה",
  smart_inbox_item: "פריט נכנס",
  timeline_item: "עדכון בציר הזמן",
  life_event: "סיפור חיים",
  command_center_item: "פריט מרכז פיקוד",
  custom_record: "פריט",
};

export const relationshipLabels: Record<EntityRelationshipType, string> = {
  belongs_to: "שייך אל",
  related_to: "קשור אל",
  created_from: "נוצר מתוך",
  converted_to: "הומר אל",
  supported_by: "מגובה על ידי",
  linked_document: "מסמך קשור",
  linked_receipt: "קבלה קשורה",
  linked_transaction: "פעולה כספית קשורה",
  linked_task: "משימה קשורה",
  linked_reminder: "תזכורת קשורה",
  linked_vehicle: "רכב קשור",
  linked_family_member: "בן משפחה קשור",
  linked_shopping_list: "רשימת קניות קשורה",
  follow_up_for: "המשך טיפול עבור",
  preparation_for: "הכנה עבור",
  result_of: "תוצאה של",
  source_of: "מקור של",
  duplicate_of: "דומה לפריט קיים",
  replaces: "מחליף",
  archived_with: "אורכב יחד עם",
  assigned_to: "משויך אל",
  paid_by: "שולם על ידי",
  created_by: "נוצר על ידי",
  reviewed_by: "נבדק על ידי",
  part_of_life_event: "חלק מסיפור חיים",
  life_event_context: "הקשר של סיפור חיים",
};

export const entityTypeRoutes: Partial<Record<EntityRelationType, AppRoute>> = {
  task: "/tasks",
  shopping_item: "/shopping",
  shopping_list: "/shopping",
  finance_transaction: "/finance",
  receipt: "/documents",
  document: "/documents",
  vehicle: "/vehicles",
  vehicle_reminder: "/vehicles",
  family_member: "/family",
  family_event: "/birthdays",
  family_knowledge: "/knowledge",
  reminder: "/tasks",
  smart_capture: "/handle",
  smart_inbox_item: "/handle",
  timeline_item: "/timeline",
  life_event: "/life",
  command_center_item: "/handle",
};

export const entityTypeIcons: Record<EntityRelationType, string> = {
  task: "✓",
  shopping_item: "🛒",
  shopping_list: "🛒",
  finance_transaction: "₪",
  receipt: "ק",
  document: "📄",
  vehicle: "🚗",
  vehicle_reminder: "🚗",
  family_member: "👥",
  family_event: "🎂",
  note: "✎",
  family_knowledge: "★",
  reminder: "⏰",
  smart_capture: "✦",
  smart_inbox_item: "↳",
  timeline_item: "↺",
  life_event: "★",
  command_center_item: "!",
  custom_record: "•",
};
