import type { IntegrationProvider } from "./types";

export const integrationCatalog: IntegrationProvider[] = [
  {
    id: "google-calendar",
    category: "calendar",
    name: "Google Calendar",
    shortName: "Calendar",
    descriptionHe: "סנכרון תאריכים ותזכורות משפחתיות ליומן.",
    descriptionEn: "Sync family dates and reminders to a calendar.",
    icon: "calendar",
    status: "setup_required",
    capabilities: ["calendar.read", "calendar.write"],
    requiresOAuth: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    docsHref: "/docs/integrations/google-calendar",
  },
  {
    id: "google-drive",
    category: "cloud-storage",
    name: "Google Drive",
    shortName: "Drive",
    descriptionHe: "אחסון מסמכים וגיבויים בענן מאובטח.",
    descriptionEn: "Store documents and backups in secure cloud storage.",
    icon: "document",
    status: "setup_required",
    capabilities: ["storage.read", "storage.write"],
    requiresOAuth: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
    docsHref: "/docs/integrations/google-drive",
  },
  {
    id: "google-contacts",
    category: "contacts",
    name: "Google Contacts",
    shortName: "Contacts",
    descriptionHe: "ייבוא אנשי קשר משפחתיים בעתיד, באישור המשתמש.",
    descriptionEn: "Import family contacts in the future, with permission.",
    icon: "family",
    status: "coming_soon",
    capabilities: ["contacts.read"],
    requiresOAuth: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "gmail",
    category: "email",
    name: "Gmail",
    shortName: "Gmail",
    descriptionHe: "שליחת הזמנות ועדכונים משפחתיים בעתיד.",
    descriptionEn: "Send invitations and family updates in the future.",
    icon: "document",
    status: "coming_soon",
    capabilities: ["email.send"],
    requiresOAuth: true,
    requiredEnv: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
  },
  {
    id: "anthropic",
    category: "ai",
    name: "Anthropic Claude",
    shortName: "Claude",
    descriptionHe: "ניתוח מסמכים וקבלות דרך שכבת AI מאובטחת.",
    descriptionEn: "Analyze documents and receipts through a secure AI layer.",
    icon: "spark",
    status: "setup_required",
    capabilities: ["ai.analyzeDocument", "ai.analyzeReceipt"],
    requiresOAuth: false,
    requiredEnv: ["ANTHROPIC_API_KEY"],
    docsHref: "/docs/integrations/anthropic",
  },
  {
    id: "gemini",
    category: "ai",
    name: "Google Gemini",
    shortName: "Gemini",
    descriptionHe: "חלופה עתידית לניתוח מסמכים וקבלות.",
    descriptionEn: "Future alternative for document and receipt analysis.",
    icon: "spark",
    status: "coming_soon",
    capabilities: ["ai.analyzeDocument", "ai.analyzeReceipt"],
    requiresOAuth: false,
    requiredEnv: ["GEMINI_API_KEY"],
  },
  {
    id: "banking-future",
    category: "banking",
    name: "Banking providers",
    shortName: "Banking",
    descriptionHe: "חיבור בנקאי עתידי לקריאה בלבד, אחרי אישורי אבטחה.",
    descriptionEn: "Future read-only banking connection after security review.",
    icon: "finance",
    status: "coming_soon",
    capabilities: ["banking.readOnly"],
    requiresOAuth: true,
  },
  {
    id: "smart-home-future",
    category: "smart-home",
    name: "Smart Home",
    shortName: "Smart Home",
    descriptionHe: "חיבורי בית חכם עתידיים לתזכורות ותובנות.",
    descriptionEn: "Future smart-home signals for reminders and insights.",
    icon: "home",
    status: "coming_soon",
    capabilities: ["smartHome.readOnly"],
    requiresOAuth: true,
  },
];

export function getIntegrationProvider(providerId: string) {
  return integrationCatalog.find((provider) => provider.id === providerId);
}

export function getVisibleIntegrationProviders() {
  return integrationCatalog.filter((provider) => provider.status !== "disabled");
}

